### ISSUE TITLE
Fix publications page

### ISSUE THREAD

**Issue by martinjvickers** [martinjvickers/website#9]
I'm not sure if it's just my browser but the google scholar link isn't working any more.

Should we go to a text version of the publications page?

**Comment by SDeans0** [comment]
Turns out that the way I was doing it has now been deprecated because it is too slow 😧
The idea was to make sure that the publications don't get out of date if we don't manually update the site often enough. I was thinking about using a github action cron job to update it e.g. once a month (cron job -> json file -> read by publications.js), but I think that a plain text version will be fine for now considering that we should just aim to get it online asap.

**Comment by martinjvickers** [comment]
Okay cool :-) The static page is merged with #10 so we can call this fixed and then maybe have a feature request to automate this in the future.
